version: '1.0.{build}'
platform:
    - x86
    - x64
    - ARM

configuration:    
    - Release
    
matrix:
    fast_finish: true
    
before_build:
    - nuget restore
    - ps: cd DigiTransit10; New-Item maps-api.txt